Us rev 3 task3
UB-ES-2020/Grup-ES pull request #134
Opened 2020-11-20 19:15 UTC by gmolinga

#112

2020-11-20 21:33 UTC, ferranSanchezUB requested changes
Esta be, m'encata que hagis utiltizat el millor codi de error de http. Nomes hi ha un canvi que sigui necessari, el resta son recomenacions.

2020-11-20 21:33 UTC, ferranSanchezUB commented on backend/resources/reviews.py
> +            return {"message": f"User with ['email': {data['email']}] Not Found"}, 404
Seria millor comprovar si el user es None abans, perque sino mai entrara degut a que g.user mai es None.
```suggestion python
        if not user:
            return {"message": f"User with ['email': {data['email']}] Not Found"}, 404

        if g.user != user:
            return {"message": "Invalid user to remove, can only be yourself"}, 401
```
Altre opcio es no comprovar-ho.
```suggestion python
        if g.user != user:
            return {"message": "Invalid user to remove, can only be yourself"}, 401
```

2020-11-20 21:33 UTC, ferranSanchezUB commented on backend/tests/test_REV_3.py
> +            json.loads(res.data)
linea que no fa res.
```suggestion python
```

2020-11-20 21:33 UTC, ferranSanchezUB commented on backend/tests/test_REV_3.py
> +            self.assertEqual(500, res.status_code)
(Canvi necessari) Mai es tindria que retornar 500, significa que la bd ha petat. Millor fer una comprovacio en el endpoint, triant per exemple un 403.

2020-11-20 21:33 UTC, ferranSanchezUB commented on backend/resources/reviews.py
> +                               f"1 to 5."}, 418
alternativa de error es 403. Pero pels memes me sembla un bon codi.

2020-11-21 09:53 UTC, gmolinga commented on backend/tests/test_REV_3.py
> +            self.assertEqual(500, res.status_code)
Vale si hauria de ser un error de client. Ho he canviat a l'últim commit.

2020-11-21 11:25 UTC, ferranSanchezUB approved these changes

2020-11-21 12:03 UTC, francinaPons approved these changes

2020-11-21 14:10 UTC, merged