US-COM-6-Task2
UB-ES-2020/Grup-ES pull request #65
Opened 2020-11-09 20:27 UTC by francinaPons

2020-11-09 21:20 UTC, ferranSanchezUB requested changes
Esta be pero has de arreglar un parell de coses i implementar el seguent:
- No se han implementat el testos unitaris del endpoint.

2020-11-09 21:20 UTC, ferranSanchezUB commented on backend/resources/transactions.py
> +    str_variable = "" if minimal else ", cannot be left blank"
No es neccesari, ja que si el parser li poses required False. mai retornara el missatge abreviat

2020-11-09 21:20 UTC, ferranSanchezUB commented on backend/resources/transactions.py
> +        data["date"] = dt.datetime.strptime(data["date"], '%Y-%m-%d')
Crec que seria millor canviar el format perque tambe s'accepti hora, minuts i segons. Ja que sino es perdra informacio. Altre opcio es suposar que en el post no se li pasara fecha i que es calculi en el model.

2020-11-10 11:40 UTC, francinaPons commented on backend/resources/transactions.py
> +        data["date"] = dt.datetime.strptime(data["date"], '%Y-%m-%d')
fet

2020-11-10 11:40 UTC, francinaPons commented on backend/resources/transactions.py
> +    str_variable = "" if minimal else ", cannot be left blank"
Fet

2020-11-10 18:21 UTC, ferranSanchezUB approved these changes
Errors corregits, ara tot be!

2020-11-10 18:40 UTC, merged